package com.example.ottintroapplication.common;

public enum MetadataCols {
    ADULT,
    BELONGS_TO_COLLECTION,
    BUDGET,
    GENRES,
    HOMEPAGE,
    ID,
    IMDB_ID,
    ORIGINAL_LANGUAGE,
    ORIGINAL_TITLE,
    OVERVIEW,
    POPULARITY,
    POSTER_PATH,
    PRODUCTION_COMPANIES,
    PRODUCTION_COUNTRIES,
    RELEASE_DATE,
    REVENUE,
    RUNTIME,
    SPOKEN_LANGUAGES,
    STATUS,
    TAGLINE,
    TITLE,
    VIDEO,
    VOTE_AVERAGE,
    VOTE_COUNT
}
